### ISSUE TITLE
Wave effect

### ISSUE THREAD

**Issue by uddhavdave** [derEisele/G213Colors#16]
Hi, i just bought this beautiful keyboard and was amazed that you guys made the software work on Linux, Great work!!

so i saw the wave effect in the software by logitech guys, but i dont see that anywhere here, is it a feature that can be implemented? I dont know how the python script works but if its possible i would love to contribute.

Thanks

**Comment by ghost** [comment]
Just a tip. You can could control the colors by holding the light button and pressing the number keys.

**Comment by uddhavdave** [comment]
Ohh i didnt know that. So this feature request doesnt make sense. Thank you. Ill close this issue.
