### ISSUE TITLE
G213colors service

### ISSUE THREAD

**Issue by gark81** [derEisele/G213Colors#6]
Hi "derEisele"

I set my G203 mouse with your code, it works with gui, but when i reboot my pc, it does not run.
i do "service systemctl enable g213colors.service", but it seems not working.

Here i put the `status`

```
● g213colors.service - Start G213Colors profile
   Loaded: loaded (/etc/systemd/system/g213colors.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2017-12-08 17:34:56 CET; 27s ago
 Main PID: 8390 (code=exited, status=1/FAILURE)
    Tasks: 0 (limit: 4915)
   CGroup: /system.slice/g213colors.service

dic 08 17:34:56 user-pc systemd[1]: Starting Start G213Colors profile...
dic 08 17:34:56 user-pc g213colors-gui[8390]: Unable to init server: Could not connect: Connection refused
dic 08 17:34:56 user-pc g213colors-gui[8390]: Unable to init server: No se pudo conectar: Connection refused
dic 08 17:34:56 user-pc g213colors-gui[8390]: Traceback (most recent call last):
dic 08 17:34:56 user-pc g213colors-gui[8390]:   File "/usr/bin/g213colors-gui", line 166, in <module>
dic 08 17:34:56 user-pc g213colors-gui[8390]:     myG.connectG()
dic 08 17:34:56 user-pc g213colors-gui[8390]: TypeError: connectG() missing 1 required positional argument: 'Name'
dic 08 17:34:56 user-pc systemd[1]: g213colors.service: Main process exited, code=exited, status=1/FAILURE
dic 08 17:34:56 user-pc systemd[1]: g213colors.service: Failed with result 'exit-code'.
dic 08 17:34:56 user-pc systemd[1]: Failed to start Start G213Colors profile.
```

**Comment by dereisele** [comment]
Hello,

I think this error is cause by a "missing" G213 keyboard. The service is a workaround to set the color of the keyboard on boot. The G203 has its own permanent memmory so that the mouse doesn't need this service. 
You just have to deactivate this service and everything should work fine.

**Comment by gark81** [comment]
I disabled the g213colors.service, open gui and set G203 color to breathe green, then i rebooted the pc and it works!

But, then, i shut down the pc for a minutes, power on the pc, and G203 reset to defaults
How could i set my config to autostart?
Do i need to edit an autotstart.sh in my user's config path?
